name: Build datasheets

on: [push, pull_request]

job:
  build:
    runs-on: ubunti-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run black to check code style consistency
        run: poetry run black . --check
      
      - name: Run Python unit tests
        run: poetry run pytest .
